### ISSUE TITLE
recyclerView.setRefreshing(true);无效，添加后无任何反应

### ISSUE THREAD

**Issue by liu-xinhui** [youlookwhat/ByRecyclerView#1]
implementation 'com.github.youlookwhat:ByRecyclerView:1.0.8'

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/69481189-07d52780-0e4a-11ea-8c4d-1e996135c69f.png)

我设置为true，并且未取消过，手机运行后没有自动下拉，需要手动下拉才能看到下拉刷新四个字

**Comment by liu-xinhui** [comment]
找到原因了，是adapter.setNewData自动隐藏了，使用addData就可以了

**Comment by youlookwhat** [comment]
非常感谢，你是第一个提issue的人，后面有问题可以随时提，我还会建立一个qq群，以方便更有效的交流，😄
