### ISSUE TITLE
GridSpaceItemDecoration 最后一项问题

### ISSUE THREAD

**Issue by zhupengxiang** [youlookwhat/ByRecyclerView#11]
![QQ图片20200305210334](https://user-images.githubusercontent.com/17894209/75984178-ded23180-5f24-11ea-9cb1-ae50535fc9fe.png)
![QQ图片20200305210353](https://user-images.githubusercontent.com/17894209/75984195-e42f7c00-5f24-11ea-8ff0-2c3b0204c535.png)

**Comment by youlookwhat** [comment]
你的RV是否使用了加载更多的呢？

**Comment by youlookwhat** [comment]
如果使用了 加载更多功能 ，那么需要设置不显示最后一个item的分割线

**Comment by zhupengxiang** [comment]
我知道了 mEndFromSize=1导致的

**Comment by youlookwhat** [comment]
额，是的，我默认设置的mEndFromSize=1，因为一般会加上加载更多。
