### ISSUE TITLE
gridLayoutManager.setSpanSizeLookup会发生错乱?

### ISSUE THREAD

**Issue by open9527** [youlookwhat/ByRecyclerView#13]
gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    //TODO:需要区分单张/多张 所占的位置,
                    if (position == 0) {
                        return 6;
                    }
                    if (position > 2 && position < 5) {
                        return 3;
                    }
                    return 2;
                }
            });

配置这个操作之后分割线显示错乱

**Comment by youlookwhat** [comment]
这个确实没处理，我抽时间处理一下~

**Comment by youlookwhat** [comment]
已处理好，更新最新的包就好了~
`implementation 'com.github.youlookwhat:ByRecyclerView:1.0.18'         // AndroidX版本引入`

**Comment by imtianx** [comment]
有没有遇到最后一行的最后一个显示的有问题
![9B194BAE-2B49-4EAD-9C1C-732AE8827393](https://user-images.githubusercontent.com/13366797/79322466-7329ae00-7f3f-11ea-9181-05b616d5cf84.png)

**Comment by youlookwhat** [comment]
默认是不显示最后一行的分割线，因为一般会使用到加载更多。
如果你没使用加载更多，请将最后一行的的分割线去掉：

```java
/**
 * 设置从哪个位置 结束设置间距
 *
 * @param startFromSize 一般为HeaderView的个数 + 刷新布局(不一定设置)
 * @param endFromSize   默认为1，一般为FooterView的个数 + 加载更多布局(不一定设置)
 */
public GridSpaceItemDecoration setNoShowSpace(int startFromSize, int endFromSize)

// endFromSize： 这个参数设置为 0
```

**Comment by imtianx** [comment]
> 默认是不显示最后一行的分割线，因为一般会使用到加载更多。
> 如果你没使用加载更多，请将最后一行的的分割线去掉：
> 
> ```java
> /**
>  * 设置从哪个位置 结束设置间距
>  *
>  * @param startFromSize 一般为HeaderView的个数 + 刷新布局(不一定设置)
>  * @param endFromSize   默认为1，一般为FooterView的个数 + 加载更多布局(不一定设置)
>  */
> public GridSpaceItemDecoration setNoShowSpace(int startFromSize, int endFromSize)
> 
> // endFromSize： 这个参数设置为 0
> ```
多谢，看了下代码已经解决了😂

**Comment by youlookwhat** [comment]
解决了就好😘
