### ISSUE TITLE
上拉加载更多的bug

### ISSUE THREAD

**Issue by LLQQHH** [youlookwhat/ByRecyclerView#14]
当你手指触碰屏幕上拉，一直到最后一个item显示出来，再继续上拉，（整个过程手指没有放开过），这个时候就会出现一个空白区块，而且也没有触发加载更多，个人认为，没有触发加载更多，应该要回弹，防止出现一个空白区块！
![TIM截图20200509150830](https://user-images.githubusercontent.com/19651932/81466809-fbca0000-9206-11ea-85d4-0c626494de4e.png)

**Comment by youlookwhat** [comment]
很懂你的意思。当时处理的时候注意到了，因为空白区块是“加载更多布局”的一种空白状态，依据它是否完全显示 并且 手指释放，来判断执行加载更多。

Ios版本微信：
一直到最后一个item显示出来，再继续上拉，会出现“加载更多布局”的加载中状态，依据它出现过 并且 手指释放，来执行加载更多。

BRVAH：
最后一个item显示就会加载更多，不存在手指释放刷新或者要最后一个item完全显示的情况。

ByRecyclerView 这样处理加载更多逻辑有利有弊，利就是不见底不加载，弊就是你说的那种情况，不到底部或者到底部不释放手指会显示空白。

我觉得 Ios版本微信 的处理逻辑可以，你觉得呢，可以的话我更新一下，修正成这个逻辑。

**Comment by youlookwhat** [comment]
已完善，和网易云音乐Android版一样，最后一行显示即加载，不必完全显示。

**Comment by bean-liu** [comment]
这个问题好像还存在

**Comment by youlookwhat** [comment]
已确认如果数据超过一页，显示最后一行的一部分松手就可以加载。

如果还有问题可能是另外的问题，能描述下具体的现象是什么吗，比如没有超过一页? @bean-liu

**Comment by bean-liu** [comment]
> 已确认如果数据超过一页，显示最后一行的一部分松手就可以加载。
> 
> 如果还有问题可能是另外的问题，能描述下具体的现象是什么吗，比如没有超过一页? @bean-liu

噢噢，我可能理解错这个主题了，我的理解是把空白状态改成默认为“显示加载更多”状态，这样就不会出现空白了，同时我也想请教如果我想让空白默认为加载更多要怎么做呢？

**Comment by youlookwhat** [comment]
空白和加载更多是不同的两个状态，你可以设置状态视图 setStateView(layout)，然后layout样式是加载更多的样式，看能不能解决问题。

**Comment by bean-liu** [comment]
我现在的情况跟发帖的同学有点类似，拖动列表拉出底部会出现一条空白的，放手后会显示加载更多，我想的是要是拖出来就显示加载更多就好了 @youlookwhat

**Comment by youlookwhat** [comment]
明白你的意思了，我可以处理一下，这个改比较简单，就是不太清楚有这样需求的人有多少，是默认就这样的机制还是通过设置状态达到

**Comment by bean-liu** [comment]
可否提示一下，我自己改下试试 @youlookwhat

**Comment by youlookwhat** [comment]
我现在想到的是，直接把ByRecyclerView里的onScrollStateChanged方法里`if`条件里的`state == RecyclerView.SCROLL_STATE_IDLE`去掉，你可以这样操作试试。
当然也有其他的方法

**Comment by youlookwhat** [comment]
@bean-liu 你改了以后可以达到效果吗

**Comment by bean-liu** [comment]
这阵子都在加班赶工，等闲下来了我试下😂@youlookwhat

**Comment by youlookwhat** [comment]
恩恩 不急不急

**Comment by bean-liu** [comment]
> 我现在想到的是，直接把ByRecyclerView里的onScrollStateChanged方法里`if`条件里的`state == RecyclerView.SCROLL_STATE_IDLE`去掉，你可以这样操作试试。
> 当然也有其他的方法

试了下不行哦

**Comment by youlookwhat** [comment]
可以看看能不能在，加载更多布局的SimpleViewHolder里处理。
我有时间了看看这个，或者你可以尝试处理下，这段时间公司有点忙，还没招到人，谅解下🥶

**Comment by bean-liu** [comment]
> 可以看看能不能在，加载更多布局的SimpleViewHolder里处理。
> 我有时间了看看这个，或者你可以尝试处理下，这段时间公司有点忙，还没招到人，谅解下🥶

没关系，我这边这个需求没有了，不用做了😂
