### ISSUE TITLE
支持多布局吗？

### ISSUE THREAD

**Issue by guoshilun** [youlookwhat/ByRecyclerView#2]
支持多布局吗？

**Comment by youlookwhat** [comment]
可以的，和原生一样，我马上补充一下示例和文档~

**Comment by guoshilun** [comment]
谢谢，可以用自己的adapter吗？还是只能用项目你们的adapter？谢谢

**Comment by youlookwhat** [comment]
@guoshilun 可以用自己的adapter 两者可以分开使用的~

**Comment by youlookwhat** [comment]
@guoshilun https://github.com/youlookwhat/ByRecyclerView/wiki#31-basebyrecyclerviewadapter 补上了多类型adapter的示例，当然你也可以使用自己的adapter实现，都是一样的。

**Comment by youlookwhat** [comment]
@guoshilun 我又增加了 线性/宫格/瀑布流的 多类型使用示例 [MultiTypeItemActivity.java](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/activity/MultiTypeItemActivity.java)
