### ISSUE TITLE
不知道有人用过ObservableList 监听修改数据没

### ISSUE THREAD

**Issue by KidAndroid** [youlookwhat/ByRecyclerView#22]
这里有个无法理解的东西，使用ObservableList通过监听自动刷新数据的时候，
    首先，new 一个空的ObservableList 对象 赋值到 adapter 并set（list 在adapter中adddatachangeCallback ,在对应方法调用对应的刷新方法），之后search 刷新数据，先clear 然后 addAll()， 如果没有设置loadmorelistener 的话它是正常刷新数据并从第一条显示的，
   但是，现在setLoadmoreListener 之后，刷新数据会导致显示到最后一条，并且loadmore view的位置也占用显示了(但是没显示文字，也没触发loadmore)，这无法理解

**Comment by youlookwhat** [comment]
是的，这里加载更多的原理是  给底部加一个view，然后滑动时监听这个view有没有显示，有的话就显示加载更多的view，然后加载数据。 setLoadmoreListener 就开启了加载更多，但是这个不显示内容的布局应该会一直在最后一行，且只有在上拉时才触发加载更多的逻辑。

**Comment by youlookwhat** [comment]
这个已经算是解决了哈，可以直接设置一个 ture 来预加载
