### ISSUE TITLE
RecyclerView 嵌套滑动置顶页面如果个给parentRecyclerView添加addFooterView页面效果会出现异常

### ISSUE THREAD

**Issue by zzzsssbo** [youlookwhat/ByRecyclerView#28]
RecyclerView 嵌套滑动置顶页面如果个给parentRecyclerView添加addFooterView页面效果会出现异常，footview出不来

**Comment by youlookwhat** [comment]
是的，parentRecyclerView不适合添加footview，因为底部是ViewPager，添加本来就很奇怪，不清楚为什么会有这样的需求，一般是在childRecyclerView里通过viewtype添加其他样式的item

**Comment by youlookwhat** [comment]
childRecyclerView添加addHeaderView和footview应该是有问题的，直接在adapter通过viewtype添加就没问题。
parentRecyclerView应该只支持添加headerview

**Comment by zzzsssbo** [comment]
好的，谢谢，再请教一个问题，像RecyclerView 嵌套滑动置顶 这个页面如果想要做成 子页面里边再套一层 tab+viewpager可以实现么

**Comment by youlookwhat** [comment]
那就是 RV-VP-RV-VP-RV了，childRecyclerView里的再套一层 tab+viewpager这种需求太奇葩了，遇到这样的需求我建议把产品经理打死。
或者强行说服他做成只加tab，下面是列表不能左右活动的那种

**Comment by zzzsssbo** [comment]
上面说的两种都是他们提出来的，疯了

**Comment by youlookwhat** [comment]
极限就是RV-VP-RV了，其他的就是局部刷新，里面再加tab+viewpager就有点过分了
