### ISSUE TITLE
GridItemDecoration使用问题

### ISSUE THREAD

**Issue by zhaoxuan365** [youlookwhat/ByRecyclerView#29]
当GridLayoutManager设置为Horizontal时，GridItemDecoration第一个和第二个条目的宽高绘制出错。有关代码和布局见附件。

![includeEdge = false](https://user-images.githubusercontent.com/20088500/117642163-93b34e80-b1b9-11eb-9481-13463aa3c681.jpg)
![includeEdge = true](https://user-images.githubusercontent.com/20088500/117642191-98780280-b1b9-11eb-8e49-d181a4665b0f.jpg)
![GridLayout 水平方向](https://user-images.githubusercontent.com/20088500/117642212-9dd54d00-b1b9-11eb-9d69-27cefa7bcc4f.png)
![activity布局](https://user-images.githubusercontent.com/20088500/117642233-a2016a80-b1b9-11eb-8751-ac10d67276f9.png)
![条目布局](https://user-images.githubusercontent.com/20088500/117642252-a594f180-b1b9-11eb-8456-ed401365f86b.png)

**Comment by youlookwhat** [comment]
GridItemDecoration里为了友好支持加载更多，默认设置了最后一个item没有分割线，你试试 setEndFromSize(0)，看是否解决。

**Comment by zhaoxuan365** [comment]
> GridItemDecoration里为了友好支持加载更多，默认设置了最后一个item没有分割线，你试试 setEndFromSize(0)，看是否解决。

可能是我之前的表述不清楚，让你误解了。我重新描述一下：当RecyclerView使用GridLayoutManager，且GridLayoutManager的方向设置为Horizontal时，使用GridItemDecoration设置分割线，列表中的第一个和第二个条目的高度和后面的不一样，并且没有对齐。PS：setEndFromSize(0)不能解决这个问题。
![微信截图_20210511102017](https://user-images.githubusercontent.com/20088500/117748579-d79e6600-b242-11eb-81fb-ec4048cdcb74.png)

**Comment by youlookwhat** [comment]
好 我看看

**Comment by youlookwhat** [comment]
是的，我没处理GridLayoutManager横向的情况，线性的横向处理了，我抽时间完善一下。紧急的话你先自己在布局里按位置处理一下哈

**Comment by zhaoxuan365** [comment]
好的。不着急，我先自己试着解决一下，等你完善后再对比一下

**Comment by youlookwhat** [comment]
恩恩 好

**Comment by youlookwhat** [comment]
已完成一半，好稍等

**Comment by zhaoxuan365** [comment]
嗯嗯，不着急

**Comment by youlookwhat** [comment]
已经解决，简单点说是在设置纵向的 上下左右间距的地方，横向的改成 左右上下。你那边是这样吗

**Comment by zhaoxuan365** [comment]
非常感谢，作者辛苦。-_-|| 我还没来得及自己试着解决 -_-||

**Comment by youlookwhat** [comment]
直接依赖 1.1.6 就好😁

**Comment by zhaoxuan365** [comment]
嗯嗯

**Comment by youlookwhat** [comment]
下关了哈，有问题再开。
