### ISSUE TITLE
parentRecyclerView添加头部布局

### ISSUE THREAD

**Issue by weixingzeng** [youlookwhat/ByRecyclerView#30]
parentRecyclerView.addHeaderView(banner);添加banner轮播图，banner无法滑动

**Comment by youlookwhat** [comment]
目前的是viewpage2+fragment+ParentRecyclerView，ParentRecyclerView的item里面是viewpage2+fragment+ChildRecyclerView

外层的viewpage2改为viewpage就可以了

**Comment by youlookwhat** [comment]
这是一个滑动冲突导致的，外层如果是viewpage2会有这个问题。可以处理viewpage2的事件分发或者改为viewpage。

先关了哈，有其他问题再提
