### ISSUE TITLE
item悬浮问题

### ISSUE THREAD

**Issue by ghost** [youlookwhat/ByRecyclerView#31]
如果给ByRecyclerView设置marginTop,item悬浮时依旧在顶部

**Comment by youlookwhat** [comment]
是的，有这样的情况，我刚改了一下，可以达到设置marginTop时item悬浮下移，但是这样也会有一个问题，就是推出去的悬浮item会盖住RecyclerView上面的布局，这样应该也是达不到要求的。

如果你只有一个悬浮的item那就是可以的

**Comment by youlookwhat** [comment]
如果你是只有一个悬浮的item，这个item不会被推走，我可以修改了提交下

**Comment by youlookwhat** [comment]
比较好的方式是通过第一个可见的position，然后控制悬浮布局的内容了

**Comment by ghost** [comment]
目前的确是只有一个item,别为了我这个改动了不必要的代码,最好弄一个通用的,可以设置四周的间距啥的

**Comment by youlookwhat** [comment]
只有一个Item，建议直接布局外层搞一个layout和悬浮的layout一致，然后控制它隐藏显示就好了哦
