### ISSUE TITLE
BaseRefreshHeader 无法适配到 SmartRefreshLayout

### ISSUE THREAD

**Issue by Mou-arch** [youlookwhat/ByRecyclerView#35]
项目使用 SmartRefreshLayout ，但是根据BaseRefreshHeader 接口的方法，没法实现两者的融合

**Comment by youlookwhat** [comment]
BaseRefreshHeader无法和SmartRefreshLayout融合，因为BaseRefreshHeader属于ByRecyclerView自定义的下拉刷新头，你应该可以将 SmartRefreshLayout 和 ByRecyclerView 配合使用，不设置ByRecyclerView下拉刷新的监听即可，你可以试试

**Comment by Mou-arch** [comment]
试了下，会存在冲突，我直接拉源码改吧

**Comment by youlookwhat** [comment]
可以哈，处理好兼容，好了我可以合一下代码
