### ISSUE TITLE
关于置顶的问题

### ISSUE THREAD

**Issue by woshigw** [youlookwhat/ByRecyclerView#37]
有个问题想请求作者
按照demo的演示关于那个  Recyclerview嵌套滑动置顶  的问题。如果点击隐藏广告悬浮位。那么此时的parentRecyclerView.setStickyListener(…)就监听不到置顶tab栏置顶的状态了
还有就是当Tab栏。按照你的demo中“Recyclerview嵌套滑动置顶”就是那个“关注”的Fragment的页面我一直往上滑动   比如这个Fragment的RecyclerView里面有100个item。我一直滑倒第50个 然后我切换到 “推荐的那个页面” 此时推荐的这个Fragment页面的RecyclerView的滑倒位置是0 我在再次往下滑  此时的Tab栏已经没有置顶了 也就说要把全部包括刚才的“关注”的Fragment 里面的滑倒高度设置为0 请问这个怎么做到呀。我看京东首页就是这样做的  意思没有置顶了 把全部设置为0

**Comment by youlookwhat** [comment]
1.parentRecyclerView.setStickyListener(…)就监听不到置顶tab栏置顶的状态了
这个我这边检查一下，我自己之前测试过，感觉是好的。其中置顶状态在变化的时候才能获取到，例如从不置顶到置顶时，一直是一个状态就不会触发。

2.关于另一个tab不置顶后，其他tab的置顶问题
我们之前处理的是，在监听变化到不置顶时，将其他tab的RV定位到第一条，这样就保证不置顶时所有的tab的数据都会在第一条

**Comment by youlookwhat** [comment]
RV置顶的方法用 recyclerView.scrollToPosition(0);

**Comment by youlookwhat** [comment]
@woshigw 我这边点了隐藏广告后可以呀，

```
binding.parentRecyclerView.setStickyListener {
    if (it){
        Log.d("111","置顶")
    }else{
        Log.d("222","不置顶")
    }
}
```

**Comment by youlookwhat** [comment]
@woshigw 还有什么问题吗

**Comment by youlookwhat** [comment]
有问题再提吧
