### ISSUE TITLE
下拉刷新的问题

### ISSUE THREAD

**Issue by woshigw** [youlookwhat/ByRecyclerView#38]
基于demo  RecyclerView 嵌套滑动置顶那个页面, 如果addHeaderView只添加一个头部。 那么如果需要下拉刷新的话只能手指滑动那个头部的View 才能下拉   至于下面的ViewPager2 就不能下拉刷新了 这是怎么回事呀大佬

**Comment by youlookwhat** [comment]
是的，嵌套滑动置顶不支持在下面的ViewPager2进行下拉刷新。如果要在下面也能下拉刷新的话就要再想其他的方式了

**Comment by youlookwhat** [comment]
有问题再开哈，这个实现就是这样的方式。
如果想实现这样的话，试试在 给的 9的示例中，将底部的RV换成ViewPager，然后在最外层使用 SmartRefreshLayout试试
