### ISSUE TITLE
作者您好，关于分割线的一个问题。

### ISSUE THREAD

**Issue by bingdu0** [youlookwhat/ByRecyclerView#39]
4.2 给宫格/瀑布流设置分割线，不能给分割线设置颜色吗？

**Comment by youlookwhat** [comment]
是的，不能设置哈，因为考虑到实际项目中大部分是只设置间隔，而间隔颜色可以通过设置背景色来完成，不知道设置背景色能不能满足你的需求~

**Comment by bingdu0** [comment]
> 是的，不能设置哈，因为考虑到实际项目中大部分是只设置间隔，而间隔颜色可以通过设置背景色来完成，不知道设置背景色能不能满足你的需求~

我是给RecyclerView 设置背景吗？还是给item？因为我的分割线是黑色的，GridLayoutManager 每行3个 ，一共有8个的时候 最后一个也是黑的。

**Comment by youlookwhat** [comment]
懂你的意思了，你是说有空白区域也用了分割线的颜色。目前这个宫格分割线解决不了你的问题了。

这样的需求有点特殊啊~

**Comment by youlookwhat** [comment]
https://www.zhangshengrong.com/p/pDXBw3z1Pd/

这一篇感觉是你想要的，你看好实现吗，有问题的话我也可以写到这个库里，然后你引用最新的版本就好了哈

**Comment by bingdu0** [comment]
> https://www.zhangshengrong.com/p/pDXBw3z1Pd/
> 
> 这一篇感觉是你想要的，你看好实现吗，有问题的话我也可以写到这个库里，然后你引用最新的版本就好了哈

这个可以 ，因为GridLayoutManager  的分割线颜色需求还是很常见的，这样就和LinearLayoutManager 保持一致了 ，即支持线也支持drawable。

**Comment by wushangjun** [comment]
> https://www.zhangshengrong.com/p/pDXBw3z1Pd/
> 
> 这一篇感觉是你想要的，你看好实现吗，有问题的话我也可以写到这个库里，然后你引用最新的版本就好了哈

我也需要设置宫格/瀑布流分割线颜色。请问怎么实现呀？看了这篇文章，不知道怎么写

**Comment by youlookwhat** [comment]
核心应该就是这个类：
public class GridDivider extends RecyclerView.ItemDecoration

然后设置一下就好了，有遇到什么问题吗，需要的话我写个demo进去

**Comment by youlookwhat** [comment]
有问题再提了~
