### ISSUE TITLE
为什么使用binding.recyclerView.setOnItemChildClickListener必须手动对holder setByRecyclerView？

### ISSUE THREAD

**Issue by liu-xinhui** [youlookwhat/ByRecyclerView#4]
![image](https://user-images.githubusercontent.com/7698511/71428403-89470080-26fb-11ea-8898-8d2913efe752.png)
![image](https://user-images.githubusercontent.com/7698511/71428416-a7146580-26fb-11ea-9c2d-f2d96f617c70.png)
这样写会报错，提示byRecyclerView为null，感觉应该可以自动绑定RecyclerView的，为什么要每次重新set？

**Comment by youlookwhat** [comment]
是的，可以自动绑定，我完善一下，非常感谢~

**Comment by youlookwhat** [comment]
@liunewshine 已经完善了，可以引入最新的版本：`ByRecyclerView:1.0.12-support`或`ByRecyclerView:1.0.12`。
有什么问题或建议可以直接提，我会随时跟进😁

**Comment by liu-xinhui** [comment]
可以了，非常感谢
