### ISSUE TITLE
不怎么好用

### ISSUE THREAD

**Issue by q88qaz** [youlookwhat/ByRecyclerView#40]
不怎么好用
上拉加载更多要拉两次，才会触发loadmore
是因为外层签到ScrollView 的关系吗？
无语

**Comment by youlookwhat** [comment]
你是在RV外面套的ScrollView吗，两个滑动冲突了肯定有问题啊

还有就是这个架子需要滑动到底部然后松手才会加载更多

**Comment by youlookwhat** [comment]
@q88qaz 已添加自动加载更多，应该可以解决你这个问题，不过外层嵌套ScrollView是不推荐的，因为得不到复用。

接入可参考demo或[文档](https://github.com/youlookwhat/ByRecyclerView#%E8%87%AA%E5%8A%A8%E5%8A%A0%E8%BD%BD%E6%9B%B4%E5%A4%9A%E9%A2%84%E5%8A%A0%E8%BD%BD)
