### ISSUE TITLE
条目点击后的水波纹效果如何设置？

### ISSUE THREAD

**Issue by smartls** [youlookwhat/ByRecyclerView#42]
作者你好，你的demo里有几个样例，有的点击会出现水波纹荡漾效果，有的则没有，我对比了几处代码，没发现关键区别。
我自己写了几个页面，都没出现波纹效果。请问具体是在哪个地方可以实现？

**Comment by Keko2025** [comment]
item 添加属性试试 android:foreground
="?android:attr/selectableItemBackgroundBorderless"



smartls ***@***.***> 于2021年12月17日周五 10:36写道：

**Comment by smartls** [comment]
> item 添加属性试试 android:foreground ="?android:attr/selectableItemBackgroundBorderless"

谢谢，我提了一个小白问题，这就关了！

**Comment by youlookwhat** [comment]
有两种设置水波纹的方式，
`android:background="?attr/selectableItemBackground"`
`android:foreground="?android:attr/selectableItemBackgroundBorderless"`

如果不生效，可以检查下是不是被子view的点击事件给覆盖了
