### ISSUE TITLE
childRecycleview 无法触发下拉刷新

### ISSUE THREAD

**Issue by ziyiren** [youlookwhat/ByRecyclerView#44]

**Comment by youlookwhat** [comment]
是的，原版就是不能触发的，我再看下另一种方案吧

**Comment by ziyiren** [comment]
另一种方案是指原版的另一种方案么？
这个能修改原版代码支持么？会不会有不能解问题

------------------ 原始邮件 ------------------
发件人: 景彬 ***@***.***&gt;
发送时间: 2022年1月17日 18:45
收件人: youlookwhat/ByRecyclerView ***@***.***&gt;
抄送: ziyiren ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [youlookwhat/ByRecyclerView] childRecycleview 无法触发下拉刷新 (Issue #44)





 
是的，原版就是不能触发的，我再看下另一种方案吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youlookwhat** [comment]
另一种方案应该是要更改页面结构了，计划使用SmartRefresh+CoordinatorLayout+ViewPager方式试试

**Comment by youlookwhat** [comment]
@ziyiren 已经上传了新的滑动置顶方案(SmartRefresh+CoordinatorLayout+ViewPager)，可以满足在childRecycleview下拉刷新的功能。
具体的类：[StickyRvCoordinatorActivity](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/activity/StickyRvCoordinatorActivity.java)

不过现在有个问题不知道影不影响，【华为手机无法将appBarLayout里面未消费完的y事件，传递到recyclerView中。】
具体可以下载最新的代码体验哈

**Comment by youlookwhat** [comment]
有问题再提哈

**Comment by ziyiren** [comment]
你好，
我这边的方案必须得用recyclerview实现，我改了一下能够支持子recyclerview能够触发下拉刷新。
现在还有一个问题想请教，手指在父recyclerview上滑到悬浮view高度，这种情况下事件应该是父recyclerview拦截了，这时候应该无法触发onnestedprescroll，是怎么做到tab停留在悬浮view下的。我在代码里好像没看到相关逻辑？
十分感谢


------------------ 原始邮件 ------------------
发件人: 景彬 ***@***.***&gt;
发送时间: 2022年1月27日 18:55
收件人: youlookwhat/ByRecyclerView ***@***.***&gt;
抄送: ziyiren ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [youlookwhat/ByRecyclerView] childRecycleview 无法触发下拉刷新 (Issue #44)





 
有问题再提哈
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by youlookwhat** [comment]
[能够支持子recyclerview能够触发下拉刷新] 你这个是怎么改的，很厉害

你下面的那个问题我还没有深入看过，你估计要自己研究了。这个问题是实现了上面的功能后的一个bug吗，还是一个额外了解的东西呢。我很想要实现上面的功能，不知道你不能贡献出源码我也看看。

**Comment by youlookwhat** [comment]
失踪了，有问题再提
