### ISSUE TITLE
RecyclerView 嵌套滑动置顶可否写一个java版本的demo

### ISSUE THREAD

**Issue by zs18340282344** [youlookwhat/ByRecyclerView#45]

**Comment by youlookwhat** [comment]
现在很多都kotlin化了，如果你在android studio里用的话很好集成的，而且ChildReclerView不需要你更改什么。

你说的是fragment需要java版本吗，因为使用的话那个地方可能会重点修改。建议学下kotlin，就可以很简单的将kotlin改为java了

**Comment by youlookwhat** [comment]
我可以将除了`ChildReclerView`这些不用改动的其他类java化，不过可能需要你提供少量的报酬，不知道你是否愿意
