### ISSUE TITLE
HookedScroller android11问题

### ISSUE THREAD

**Issue by Lancerer** [youlookwhat/ByRecyclerView#48]
HookedScroller这个类中的durationField属性，在android11使用时报错反射问题：Caused by: java.lang.reflect.InvocationTargetException

**Comment by youlookwhat** [comment]
能具体描述下怎么使用的，还有机型吗，我好复现下。我用oppo的android11手机还没发现问题

**Comment by Lancerer** [comment]
你把你的demo的compileSdkVersion 和targetSdkVersion改成30，然后用11手机试试 CoordinatorLayout 嵌套滑动置顶这个activity，直接奔溃

**Comment by youlookwhat** [comment]
好的   我试试，麻烦了

**Comment by youlookwhat** [comment]
不好意思，有点久了。
有3个方案可以解决你的问题：
 1、targetSdkVersion 在30以下。因为HookedScroller反射失败
 2、集成三方库：[FreeReflection](https://github.com/tiann/FreeReflection)。需要minSdkVersion 21
 3、现已经对代码做了容错处理，你可以照里面修正下。然后demo也给了原始版本，你可以体验下。不过这个没有[滑动头部布局不置顶]了

相关代码：[HookedScroller.kt](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/stickrvcool/HookedScroller.kt)

**Comment by youlookwhat** [comment]
有问题再提哈~
