### ISSUE TITLE
增加头布局后，设置滚动到第一个item位置错误

### ISSUE THREAD

**Issue by chengzhuangjie** [youlookwhat/ByRecyclerView#49]

**Comment by youlookwhat** [comment]
你设置滚动到第一个item位置的代码是啥，你的第一个item不包含头布局吧，你是不是没有去掉头布局

**Comment by chengzhuangjie** [comment]
大概就是现在页面类似一个头部帖子，底部评论内容，插入一个评论，想要插入评论的效果，就设置了滚动到顶部，问题就是加了头布局后滚动到评论的位置是错误，按照你说的解决办法就是先移除头部再设置滚动吗

**Comment by youlookwhat** [comment]
你是想说发布评论后，定位到发的评论那条位置吗。你需要加上头部的position

定位的位置：position + recyclerView.getCustomTopItemViewCount()

position ：不添加头部时，要定位的位置
getCustomTopItemViewCount() ： 头部布局(如果有下拉刷新布局也包含)的个数

**Comment by youlookwhat** [comment]
@chengzhuangjie 问题解决了吗

**Comment by youlookwhat** [comment]
还有问题再提哈
