### ISSUE TITLE
fileAdapter.getItemData(i)
报错
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by chengzhuangjie** [youlookwhat/ByRecyclerView#52]

**Comment by youlookwhat** [comment]
感谢反馈，是的，小概率会发生这样的问题，我马上处理一下发一个版本

**Comment by youlookwhat** [comment]
@chengzhuangjie 可以依赖最新的版本哈：`implementation 'com.github.youlookwhat:ByRecyclerView:1.3.1'`

然后需要对`getItemData()`得到的数据做下非空判断。
