### ISSUE TITLE
cvc-complex-type.2.4.a: 发现了以元素 'base-extension' 开头的无效内容。应以 '{layoutlib}' 之一开头。

### ISSUE THREAD

**Issue by SunSeekerX** [youlookwhat/ByRecyclerView#53]
git 拉下来跑不起来

**Comment by youlookwhat** [comment]
你应该是装了新版本的 Android Studio 运行老的项目出现的问题。
建议改成项目中的gradle版本试试，以及网上其他人的反馈：https://blog.csdn.net/jzlhll123/article/details/123490512

**Comment by SunSeekerX** [comment]
这个问题解决了。确实是要用jdk 1.8 
然后我升级了 gradle。现在项目内这个应该比较老了。
可以看看升级之后的代码，我放在我自己的 git 了
https://gogs.yoouu.cn/android/ByRecyclerView

**Comment by youlookwhat** [comment]
可以
