### ISSUE TITLE
jcenter() 弃用

### ISSUE THREAD

**Issue by SunSeekerX** [youlookwhat/ByRecyclerView#54]
jcenter() 可以使用 mavenCentral() 替换

**Comment by youlookwhat** [comment]
我使用mavenCentral()替换后运行不起来，你是装了新版的AndroidStudio 出的问题吧

**Comment by SunSeekerX** [comment]
https://juejin.cn/post/7053774607160967199 迁移指南

**Comment by youlookwhat** [comment]
这个很早就看过了，自己的项目都在jitpack里，三方的如果是jcenter()就换成mavenCentral()或者是jitpack。

**Comment by youlookwhat** [comment]
看来没问题了，有问题了再提吧
