### ISSUE TITLE
只有一项内容的时候 底部会有空项

### ISSUE THREAD

**Issue by boge-mvp** [youlookwhat/ByRecyclerView#6]
当我监听了上拉加载更多的时候  如果当前只有一个项  底部会多一个空白的项    
setNotFullScreenNoLoadMore() 我也设置了的  但是这个只能禁止上拉  空白的项还是在

**Comment by youlookwhat** [comment]
这个是会多出来的，留的那部分空白布局就是没有内容的加载更多布局，这样的话，在多出一屏的时候会显示加载中的状态，然后再显示内容。
我也可以不让它显示出来，那么造成的后果是，超过一屏上拉的时候底部就看不到加载中的效果了。

你现在是不想要显示那一块空白的加载更多布局吗，不设置加载更多监听就可以了。

**Comment by boge-mvp** [comment]
我就是希望在不满足全屏的时候  那个空白的项可以隐藏   然后用手下拉的时候  在显示出来更多 加载完成后那个空白项又会消失掉，或者你的这个下拉可以不可以做成那种  那个底部加载更多 是在用手拉后才显示的  默认不显示出来

**Comment by youlookwhat** [comment]
不满足全屏的时候空白的项存在对你是有什么影响吗？

我可以在不满一屏的时候让空白的项消失，上拉的时候才出现。
但是超过一屏后空白的项是不能消失的，因为那一块会显示下一次请求的内容，如果消失，正在加载中的状态就会看不到了，并且内容就会显示在屏幕的下方，用户会感知不到是否加载成功了。

其实我认为有个空白项不会存在什么问题，我想知道你为什么想这样做。

**Comment by boge-mvp** [comment]
![QQ图片20200208144921](https://user-images.githubusercontent.com/6498301/74080851-3b0b7800-4a83-11ea-9e6c-3212c7e9498f.png)

**Comment by youlookwhat** [comment]
明白你的意思，你是加了分割线itemDecoration，然后多了一行会多显示一行分割线。
你可以处理一下，将最后一行的分割线去掉。

此项目中自带了分隔线，可以适用于线性/宫格/瀑布流，可以让最后一行的分割线不显示，也可以让前面的几个item的分割线不显示(加header的情况下)，具体请看这里：https://github.com/youlookwhat/ByRecyclerView/wiki#4-itemdecoration
