### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by renhuan** [youlookwhat/ByRecyclerView#63]
当data数据为空的时候，
```
            recyclerView.setEmptyView(emptyLayoutId)
            recyclerView.setNotFullScreenNoLoadMore()
            recyclerView.setEmptyViewEnabled(true)
            recyclerView.isLoadMoreEnabled = false //这句会报错
```
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionSimpleViewHolder{c48e259 position=2 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} me.jingbin.library.ByRecyclerView{b86ec9a VFED..... ......ID 0,0-1080,1920 #7f080072 app:id/byRecyclerView}, adapter:me.jingbin.library.ByRecyclerView$WrapAdapter@da5d9cb, layout:androidx.recyclerview.widget.LinearLayoutManager@5fbc5a8,
```

**Comment by renhuan** [comment]
> 当data数据为空的时候，
> 
> ```
>             recyclerView.setEmptyView(emptyLayoutId)
>             recyclerView.setNotFullScreenNoLoadMore()
>             recyclerView.setEmptyViewEnabled(true)
>             recyclerView.isLoadMoreEnabled = false //这句会报错  如果为true不会报错
> ```
> 
> ```
> java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionSimpleViewHolder{c48e259 position=2 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} me.jingbin.library.ByRecyclerView{b86ec9a VFED..... ......ID 0,0-1080,1920 #7f080072 app:id/byRecyclerView}, adapter:me.jingbin.library.ByRecyclerView$WrapAdapter@da5d9cb, layout:androidx.recyclerview.widget.LinearLayoutManager@5fbc5a8,
> ```

**Comment by youlookwhat** [comment]
好的，我这边看看

**Comment by youlookwhat** [comment]
- 有人在这个项目中提了类似的issus:https://github.com/youlookwhat/ByRecyclerView/issues/26

- 这是RecyclerView的一个Bug：[滑动RecyclerView时出现异常： java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item posit](https://blog.csdn.net/chenli_001/article/details/85232551?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-85232551-blog-79570563.pc_relevant_3mothn_strategy_and_data_recovery&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-85232551-blog-79570563.pc_relevant_3mothn_strategy_and_data_recovery&utm_relevant_index=1)

解决方法：
1、Demo已经提供了[ByLinearLayoutManager](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/view/ByLinearLayoutManager.java)，可以将LinearLayoutManager替换为它
2、在代码最后加上`mAdapter.setNewData(null);`
```
            recyclerView.setEmptyView(emptyLayoutId)
            recyclerView.setNotFullScreenNoLoadMore()
            recyclerView.setEmptyViewEnabled(true)
            recyclerView.isLoadMoreEnabled = false 
            mAdapter.setNewData(null)
```
可以试试~ @renhuan

**Comment by renhuan** [comment]
好的，多谢

**Comment by csh159** [comment]
isRefreshEnabled = false 设置也是会报上面的错，用ByLinearLayoutManager可能会导致数据错乱，有什么好的办法解决吗？

**Comment by youlookwhat** [comment]
> isRefreshEnabled = false 设置也是会报上面的错，用ByLinearLayoutManager可能会导致数据错乱，有什么好的办法解决吗？

用ByLinearLayoutManager数据错乱应该是其他的问题，不是这个类导致的，建议你检查下数据错乱的愿意

**Comment by csh159** [comment]
> > isRefreshEnabled = false 设置也是会报上面的错，用ByLinearLayoutManager可能会导致数据错乱，有什么好的办法解决吗？
> 
> 用ByLinearLayoutManager数据错乱应该是其他的问题，不是这个类导致的，建议你检查下数据错乱的愿意

你可以测试下，多种布局情况，加载一页不要滑列表，然后请求上一页数据关闭刷新功能，用ByLinearLayoutManager会导致数据不一致的情况。还发现个问题，刷新的关闭与打开scrollToPosition里面的position不一样。我这么写才是正确的 binding.chatRecyclerView.scrollToPosition(adapter.itemCount - if (binding.chatRecyclerView.isRefreshEnabled) 0 else 1)，也就是移到最底部的一个位置，而不能直接写scrollToPosition（adapter.itemCount -1）

**Comment by youlookwhat** [comment]
就算你用系统的LinearLayoutManager也应该有数据不一致的问题，因为ByLinearLayoutManager就把系统的方法拿过来try了一下而已，而且[java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item posit](https://blog.csdn.net/chenli_001/article/details/85232551?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-85232551-blog-79570563.pc_relevant_3mothn_strategy_and_data_recovery&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-85232551-blog-79570563.pc_relevant_3mothn_strategy_and_data_recovery&utm_relevant_index=1)，是官方RecyclerView的bug。设置isRefreshEnabled后要使用 adatper.setNewData()刷新。


第二个是的，scrollToPosition里的position是不一样，实际上下拉刷新头占用一个item。可以这样写：scrollToPosition(adapter.itemCount+recyclerView.getCustomTopItemViewCount()-1)
