### ISSUE TITLE
setStackFromEnd = true 下拉刷新有点不正常

### ISSUE THREAD

**Issue by wzJun1** [youlookwhat/ByRecyclerView#64]
```
LinearLayoutManager layoutManager = new LinearLayoutManager(activity);
layoutManager.setOrientation(RecyclerView.VERTICAL);
layoutManager.setStackFromEnd(true);
recyclerView.setLayoutManager(layoutManager);
```

demo里的RefreshFragment中加一句
`layoutManager.setStackFromEnd(true);`
也是一样，下拉刷新不太正常

**Comment by wzJun1** [comment]
这里有问题吧
`ev.setAction(MotionEvent.ACTION_DOWN);`

**Comment by youlookwhat** [comment]
好的 我看看

**Comment by youlookwhat** [comment]
这一块是有问题，去掉`ev.setAction(MotionEvent.ACTION_DOWN);`也会存在问题，这个问题不太好解决，暂时没有好的解决方案。

这样看来自带的下拉刷新不太适配一些特殊的场景，如果一定要使用`setStackFromEnd ()`，建议你使用[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)试试~

**Comment by youlookwhat** [comment]
使用[SmartRefreshLayout](https://github.com/scwang90/SmartRefreshLayout)可只改下拉刷新，加载更多应该不会受到影响。

**Comment by wzJun1** [comment]
可以说一下如果去掉了还存在什么问题吗？我目前改成了ACTION_MOVE，没有发现异常。
我这边是聊天页面，使用setStackFromEnd倒序聊天记录，下拉加载历史记录。如果有其他问题我再考虑解决办法，目前来看还是很顺滑的。

**Comment by youlookwhat** [comment]
去掉的话，一直按住列表然后下拉再上滑出屏幕外，连续几次会出现问题，有时候可能下拉刷新的ui一直显示，我这边情况是这样

**Comment by wzJun1** [comment]
哦，原来这样.. 我这边没有这个问题，复现不出。不过我没有去掉，我是改成了ev.setAction(MotionEvent. ACTION_MOVE);

**Comment by youlookwhat** [comment]
我改成`ev.setAction(MotionEvent. ACTION_MOVE);`了试试..

**Comment by youlookwhat** [comment]
还是会有一样的问题。除非下拉头出现就刷新，不能按住上下一直滑动。

一直按住列表然后下拉再上滑出屏幕外，松手，就会出现下拉刷新布局一直显示

**Comment by wzJun1** [comment]
😅我在你demo里试了一下，也是没有你那个问题，或者是我没找出来，看看视频是不是你说的那么操作的。

https://z7v-assistant-1304081409.cos.ap-chongqing.myqcloud.com/Record_2022-10-24-19-04-38_5658a21d7d5c73ce8e1bfeb687ec562d.mp4

**Comment by youlookwhat** [comment]
https://user-images.githubusercontent.com/15052574/197520008-d1d49fe8-5c02-4859-aa8f-1571cb6c2cfd.mp4

@wzJun1

**Comment by wzJun1** [comment]
😅下拉的视图卡在了那里是吗？ 为什么我这里不会这样呢～～也是直接clone你1.3.6的demo

确实没弄出那个问题，我拿小米和OPPO vivo都试了。

算了，先这样吧，不知道啥原因，我这里暂时没有问题。如果你得空解决了我再Update

**Comment by youlookwhat** [comment]
好，那先放着了😄

**Comment by youlookwhat** [comment]
有问题了再开哈~
