### ISSUE TITLE
可以增加一个treeview的的适配器吗

### ISSUE THREAD

**Issue by greglee0** [youlookwhat/ByRecyclerView#65]
我发现byrecyclerview还没有treeview的适配器
，市面上的treeview感觉不怎么好用
。如果byrecyclervjew能加上这个那就更好了！

**Comment by youlookwhat** [comment]
treeview 是指多级列表吗

**Comment by greglee0** [comment]
是的

**Comment by youlookwhat** [comment]
是的 多级列表对于独立开发者基本是刚需了，很早以前准备完善了，换电脑代码忘提交了一直放着在，这段时间我再看看

**Comment by greglee0** [comment]
OK
