### ISSUE TITLE
希望增加一个功能

### ISSUE THREAD

**Issue by greglee0** [youlookwhat/ByRecyclerView#67]
希望此项目增加一个阻尼回弹的库

**Comment by youlookwhat** [comment]
具体是什么效果，有对应的功能参考吗

**Comment by greglee0** [comment]
就类似于miui13的那个列表阻尼回弹

**Comment by youlookwhat** [comment]
我看Android12版本的oppo系统上也有列表阻尼回弹的效果。
这种需求太过独特，且是厂商自定义相关，不适用大部分人；而且还有很多功能待添加呢：
 - 多级列表
 - 侧滑删除
 - 长按排序

所以短期内应该不会加这个阻尼效果了

**Comment by greglee0** [comment]
好的
