### ISSUE TITLE
Demo中可以增加字母索引的案例吗

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [youlookwhat/ByRecyclerView#71]
Demo中可以增加字母索引的案例吗，类似微信通讯录那样

**Comment by youlookwhat** [comment]
这个其实和RecyclerView没关系的，我们项目中有用到这个索引，是用的这个库：https://github.com/saiwu-bigkoo/Android-QuickSideBar

你可以试试这个~ @Lee-Wang-Jing

**Comment by Lee-Wang-Jing** [comment]
好的，非常感谢~
