### ISSUE TITLE
NestedScrollView内嵌套ByRecyclerView时，会导致下拉刷新和拖动ByRecyclerView向上的动作冲突

### ISSUE THREAD

**Issue by AlwaysFHao** [youlookwhat/ByRecyclerView#78]
表现形式为，触底加载后，回拉会先触发下拉刷新操作，然后直接就刷新会第一页了

**Comment by youlookwhat** [comment]
- 不建议NestedScrollView嵌套ByRecyclerView且使用下拉刷新/加载更多等操作，因为嵌套后会导致RecyclerView里的内容不会被复用。
- 基本是在ByRecyclerView基础上使用**addHeaderView**的方式作为页面结构。
- NestedScrollView嵌套ByRecyclerView只适用于RecyclerView里内容很少的情况。

**Comment by AlwaysFHao** [comment]
好的，感谢🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月16日 22:59 |
| 收件人 | youlookwhat/ByRecyclerView ***@***.***> |
| 抄送人 | AlwaysFHao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [youlookwhat/ByRecyclerView] NestedScrollView内嵌套ByRecyclerView时，会导致下拉刷新和拖动ByRecyclerView向上的动作冲突 (Issue #78) |

不建议NestedScrollView嵌套ByRecyclerView且使用下拉刷新/加载更多等操作，因为嵌套后会导致RecyclerView里的内容不会被复用。
基本是在ByRecyclerView基础上使用addHeaderView的方式作为页面结构。
NestedScrollView嵌套ByRecyclerView只适用于RecyclerView里内容很少的情况。
