### ISSUE TITLE
感谢开源

### ISSUE THREAD

**Issue by ad5566** [youlookwhat/ByRecyclerView#8]
大神的库不错，目前功能相对其他类似的库还是有点少，如：头部悬浮吸顶功能，设置滑动列表动画，item滑动删除等，不知道大神有考虑增加这些功能吗？

**Comment by youlookwhat** [comment]
这些正在添加呢，头部悬浮吸顶功能加入了但是有点小问题，所以没提及，列表动画，滑动删除之后都会添加的~

**Comment by ad5566** [comment]
哇，期待更新

**Comment by youlookwhat** [comment]
头部悬浮吸顶功能已完善~
