### ISSUE TITLE
When ByRecyclerView data exceeds 50, the drop-down refresh becomes slow

### ISSUE THREAD

**Issue by tanglinyan** [youlookwhat/ByRecyclerView#81]
When ByRecyclerView data exceeds 50, the drop-down refresh becomes slow.
Caton is unacceptable for practical applications
version:1.4.1

**Comment by youlookwhat** [comment]
Do you want to use automatic refresh or manual refresh? In our company's project, among more than 100 data streams of waterfall, manual pull-down refresh has not found the phenomenon of lag. My mobile phone is OPPO Find X3 Pro, Android14.

Are you using automatic refresh, or are you using Android14 for debugging?


--- 
你是使用自动刷新还是手动刷新，在我们公司的项目中，瀑布流100多条数据中，进行手动的下拉刷新还没发现卡顿的现象，我的手机是OPPO Find X3 Pro，Android14。

你出现卡顿的现象，是使用的是自动刷新吗，或者是使用的是Android14调试的吗

**Comment by tanglinyan** [comment]
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/6e37ce18-ac4d-4947-b879-8deae6006154">
I wrote it in the demo

**Comment by tanglinyan** [comment]
<img width="817" alt="image" src="https://github.com/user-attachments/assets/9782d951-f50a-40ee-9d28-1e30881d56e1">
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/d6d685bb-1495-49f2-8830-ee7a82c5927d">
This is my code logic
The device used is oppo pad air2

**Comment by tanglinyan** [comment]
The device is android 14
When the data is more than 50, it becomes significantly sluggish

**Comment by youlookwhat** [comment]
Looking at your code, this is the wrong way to use RecyclerView. RecyclerView should not be embedded directly in LinearLayout or RelativeLayout. This will cause the itemView inside to not be reused.Too much data will lead to stalling.

The correct way to use it is that the layout above RecyclerView is implemented using addHeaderView. Reference class：[HeaderFooterActivity.java](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/activity/HeaderFooterActivity.java)

---
看到了你的代码，这是你使用RecyclerView的方式不对，RecyclerView最好不要直接嵌入在 LinearLayout或者RelativeLayout内，这样会导致里面的itemView不会被复用。数据量多后就会导致卡顿。

正确的使用方式是，RecyclerView上面的布局通过 addHeaderView的方式实现。参考类：[HeaderFooterActivity.java](https://github.com/youlookwhat/ByRecyclerView/blob/master/app/src/main/java/me/jingbin/byrecyclerview/activity/HeaderFooterActivity.java)

**Comment by youlookwhat** [comment]
> <img alt="image" width="817" src="https://private-user-images.githubusercontent.com/33612347/387077811-9782d951-f50a-40ee-9d28-1e30881d56e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTM0MDIsIm5iZiI6MTczMTkxMzEwMiwicGF0aCI6Ii8zMzYxMjM0Ny8zODcwNzc4MTEtOTc4MmQ5NTEtZjUwYS00MGVlLTlkMjgtMWUzMDg4MWQ1NmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA2NTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDRhNzNmZjhlYTU4YjdlMTAyZGFjZDM2M2RkYWEwNWM4ZDIxYzdlZTlkODlmNDhhMGU4YmQxMWZmOTU3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZJMGF7YOsubI1SuqwFCZtX5uizCXRdc1GAW9zm3ydVM"> <img alt="image" width="1224" src="https://private-user-images.githubusercontent.com/33612347/387077976-d6d685bb-1495-49f2-8830-ee7a82c5927d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTM0MDIsIm5iZiI6MTczMTkxMzEwMiwicGF0aCI6Ii8zMzYxMjM0Ny8zODcwNzc5NzYtZDZkNjg1YmItMTQ5NS00OWYyLTg4MzAtZWU3YTgyYzU5MjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA2NTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhOGIzYjc4YTFmY2E0NDFkYjU5MTZiOGE2ZjEyODY0OTE0YmMyMDFiZjhhNzc5MWFjOTM3NjQzMGFmNTY2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.haoCjCmV51oLqayHZ6_Dq3_YwEb2s1wiceMu6KchHyo"> This is my code logic The device used is oppo pad air2

Can you see the outermost layout of this xml

In addition, if you debug on the Android14 mobile phone, the application itself will be very card, which is a system bug in Android14.

---
能看下这个xml的最外层布局吗

另外如果在Android14手机上进行调试时，本身应用就会很卡，这是Android14的一个系统bug.

**Comment by tanglinyan** [comment]
It's already the outer layer, and the outermost layer is DataBinding.
I didn't debug it, but the apk is currently packaged in debug mode.

**Comment by youlookwhat** [comment]
Can you call an apk, install it on your phone. Or try it with an Android 14 or below.

**Comment by tanglinyan** [comment]
Can I join your qq group

**Comment by youlookwhat** [comment]
my qq: 770423177
CloudReader group:727379132

**Comment by tanglinyan** [comment]
android:layout_height="match_parent"
android:layout_below="@id/ll_search_info"
The fetched height causes the pull-down refresh to become slow.

**Comment by tanglinyan** [comment]
android:layout_weight = "1"
android:layout_height="0dp" 
Using this method is solved
