### ISSUE TITLE
能否增加骨架屏loading动画

### ISSUE THREAD

**Issue by liu-xinhui** [youlookwhat/ByRecyclerView#9]

**Comment by youlookwhat** [comment]
可以的，这个功能不太复杂，近期会更新出来

**Comment by youlookwhat** [comment]
@liunewshine 已经完成了，具体可见 https://github.com/youlookwhat/ByRecyclerView/wiki#6-%E8%AE%BE%E7%BD%AEskeleton%E9%AA%A8%E6%9E%B6%E5%9B%BE

简单配置即可实现。

**Comment by liu-xinhui** [comment]
嗯嗯，明天试试
